# ################################################
# DriveBackupV2   -   by Max Maeder (MaxTheGinus)
# ################################################

# DOCUMENTATION HAS MOVED
# Now available online at: https://github.com/MaxMaeder/DriveBackupV2/wiki

version: 2

delay: 60
backup-thread-priority: 1
keep-count: 20
local-keep-count: 0
zip-compression: 1
backups-require-players: true
disable-saving-during-backups: true

scheduled-backups: true
schedule-timezone: +07:00
backup-schedule-list:
- days: 
  - "everyday"
  time: "00:00"

backup-list:
- path: .
  format: "Backup-server-%FORMAT.zip"
  create: true

local-save-directory: backups
remote-save-directory: backups

googledrive:
  enabled: true
  shared-drive-id: ''
onedrive:
  enabled: false
dropbox:
  enabled: false
webdav:
  enabled: false
  hostname: http://example.com/directory
  username: Username
  password: Password
nextcloud:
  enabled: false
  hostname: https://example.com/remote.php/dav/files/user/
  username: Username
  password: Password
  chunk-size: 20000000
ftp:
  enabled: false
  hostname: ftp.example.com
  port: 21
  sftp: false
  ftps: false
  username: Username
  password: Password

messages:
  send-in-chat: true
  prefix: '&6[&4DriveBackupV2&6] '
  default-color: '&3'

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  debug: false
  date-language: en
  date-timezone: +07:00
  ftp-file-separator: /
